package my.rentCar;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.*;
import javax.swing.event.*;
import javax.swing.table.DefaultTableModel;


import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;

import javax.swing.JButton;

public class FindCar extends javax.swing.JPanel {

	MainGui parent;
    public FindCar(MainGui parent) {
    	this.parent = parent;
        cal1=new MemoCalendar(this);
        cal1.mode=MemoCalendar.BOOKING;
         cal2=new MemoCalendar(this);
         cal2.mode=MemoCalendar.RETURN;
        initComponents();
        
        this.bkPanel.setLayout(new BorderLayout());
        this.bkPanel.add(cal1.mainPanel);
        
        this.rePanel.setLayout(new BorderLayout());
        this.rePanel.add(cal2.mainPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        btCS = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btMyPage = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rbtAirport = new javax.swing.JRadioButton();
        rbtSGP = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bkPanel = new javax.swing.JPanel();
        rePanel = new javax.swing.JPanel();
        taNotice = new javax.swing.JTextArea();
        btNext = new javax.swing.JButton();
        btPre = new javax.swing.JButton();
        tfBooking = new javax.swing.JTextField();
        tfReturn = new javax.swing.JTextField();
        dao=new CarDAO();
        selectCar = new SelectCar(parent);
        //selectCar=new SelectCar();

       // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //setResizable(false);
        setSize(new java.awt.Dimension(500, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));
        //jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(card);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 700));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        
        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        
        lbLogo.setIcon(new javax.swing.ImageIcon("src/images/LOGO3.png")); // NOI18N

        btCS.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btCS.setText("고객센터");
        btCS.setBorder(null);
        btCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCSActionPerformed(evt);
            }
        });

        btLogout.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btLogout.setText("Logout");
        btLogout.setBorder(null);
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btMyPage.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btMyPage.setText("MyPage");
        btMyPage.setBorder(null);
        btMyPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btMyPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCS, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btMyPage, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btMyPage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        group.add(rbtAirport);
        rbtAirport.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        rbtAirport.setText("제주공항점");
        rbtAirport.setBackground(new java.awt.Color(255, 204, 102));
        rbtAirport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtAirportItemStateChanged(evt);
            }
        });
        rbtAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAirportActionPerformed(evt);
            }
        });

        group.add(rbtSGP);
        rbtSGP.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        rbtSGP.setText("서귀포점");
        rbtSGP.setBackground(new java.awt.Color(255, 204, 102));
        rbtSGP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtSGPItemStateChanged(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        
        bkPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        javax.swing.GroupLayout bkPanelLayout = new javax.swing.GroupLayout(bkPanel);
        bkPanel.setLayout(bkPanelLayout);
        bkPanelLayout.setHorizontalGroup(
            bkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        bkPanelLayout.setVerticalGroup(
            bkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("대여일", bkPanel);

        rePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout rePanelLayout = new javax.swing.GroupLayout(rePanel);
        rePanel.setLayout(rePanelLayout);
        rePanelLayout.setHorizontalGroup(
            rePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        rePanelLayout.setVerticalGroup(
            rePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("반납일", rePanel);

        taNotice.setEditable(false);
        taNotice.setColumns(20);
        taNotice.setRows(5);
        taNotice.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        taNotice.setText("주의사항\n당일 취소 안됨\n등등");

        btNext.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btNext.setText("다음");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        btPre.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btPre.setText("이전");
        btPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreActionPerformed(evt);
            }
        });

        for(int i=0 ; i<6 ; i++){
         for(int j=0 ; j<7 ; j++){
            cal1.dateButs[i][j].addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                  dateButsActionPerformed(evt);
               }
            });
         }
      }//booking-----------------------------------------
        
        for(int i=0 ; i<6 ; i++){
           for(int j=0 ; j<7 ; j++){
              cal2.dateButs[i][j].addActionListener(new java.awt.event.ActionListener() {
                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dateButsActionPerformed(evt);
                 }
              });
           }
        }//return------------------------------------------
        
        tfBooking.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        tfBooking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBooking.setText(cal1.sDate);
        tfBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "대여일", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 14))); // NOI18N
        tfBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBookingActionPerformed(evt);
            }
        });

        tfReturn.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        tfReturn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfReturn.setText(cal2.sDate);
        tfReturn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "반납일", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 14))); // NOI18N
        tfReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btPre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtSGP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(tfBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(taNotice, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtSGP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(taNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, "card2");
        //jPanel1.add(selectCar.jPanel1,"selectPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        //pack();
    }// </editor-fold>                        

    private void tfBookingActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rbtSGPItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void rbtAirportActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void rbtAirportItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btMyPageActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	parent.card.show(parent.jPanel1, "my");
    }
    
    private void btCSActionPerformed(java.awt.event.ActionEvent evt) {                                     
    	parent.card.show(parent.jPanel1, "faq");
    }                                    

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	parent.card.show(parent.jPanel1, "main");
    	parent.tfId.setText("");
    	parent.tfPwd.setText("");
    }                                        

    private void btPreActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	parent.card.show(parent.jPanel1, "main");
    }                                     

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {
        loc=(rbtAirport.isSelected())?rbtAirport.getText():rbtSGP.getText();
        System.out.println(loc);
        if(loc==null) {
           return;
        }
        showSelectedCar();
        parent.card.show(parent.jPanel1, "select");
        //card.show(main.jPanel1, "selectPanel");
    }                                      

   public void showSelectedCar() {
      try {
         ArrayList<CarVO> cList=dao.listCar(loc);
         showCarTable(cList);
      } catch (SQLException e) {
         // TODO Auto-generated catch block
         System.out.println("showSelectedCar() error: "+e.getMessage());
      }
      
   }

   public void showCarTable(ArrayList<CarVO> cList) {
       Object [][]data=new Object[cList.size()][6];//2차원 배열 생성
        
        //ArrayList에 저장된 데이터를 2차원 배열에 옮기자
        for(int i=0; i<data.length; i++) {
           CarVO cvo=cList.get(i);
           data[i][0]=cvo.getCarIdx();
           data[i][1]=cvo.getCarNum();
           data[i][2]=cvo.getCarName();
           data[i][3]=cvo.getLoc();
           data[i][4]=cvo.getCarInfo();
        }
        //테이블 모델
        dmodel=new DefaultTableModel(data,colHeader);
        
        //뷰와 모델을 연결
        parent.selectConn.jTable1.setModel(dmodel);
    }
    
    private void tfReturnActionPerformed(java.awt.event.ActionEvent evt) {
       
    }
    
    private void dateButsActionPerformed(java.awt.event.ActionEvent evt) {
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FindCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    javax.swing.JPanel bkPanel;
    javax.swing.JButton btCS;
    javax.swing.JButton btLogout;
    javax.swing.JButton btMyPage;
    javax.swing.JButton btNext;
    javax.swing.JButton btPre;
    javax.swing.ButtonGroup group;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JLabel lbLogo;
    javax.swing.JRadioButton rbtAirport;
    javax.swing.JRadioButton rbtSGP;
    javax.swing.JPanel rePanel;
    javax.swing.JTextArea taNotice;
    javax.swing.JTextField tfBooking;
    javax.swing.JTextField tfReturn;
    CardLayout card=new CardLayout();
    SelectCar selectCar;
    MemoCalendar cal1;
    MemoCalendar cal2;
    CarDAO dao;
    String loc;
    Date bk_day, re_day;
    DefaultTableModel dmodel;
    String []colHeader= {"번호","차량번호","차량이름","지점","설명"};
    // End of variables declaration                   
}